<?php
##########################################
###### Generated MySQL-Config-File #######
##########################################
define('BS_MYSQL_HOST','localhost');
define('BS_MYSQL_LOGIN','root');
define('BS_MYSQL_PASSWORD','');
define('BS_MYSQL_DATABASE','bs_122_online');
##########################################

############## MySQL-Tables ############
define('BS_TB_ACP_ACCESS','ssf_acp_access');
define('BS_TB_ACTIVATION','ssf_activation');
define('BS_TB_ATTACHMENTS','ssf_attachments');
define('BS_TB_AVATARS','ssf_avatars');
define('BS_TB_BANS','ssf_banlist');
define('BS_TB_BBCODES','ssf_bbcodes');
define('BS_TB_BOTS','ssf_bots');
define('BS_TB_CACHE','ssf_cache');
define('BS_TB_CHANGE_EMAIL','ssf_change_email');
define('BS_TB_CHANGE_PW','ssf_change_pw');
define('BS_TB_CONFIG','ssf_cfg');
define('BS_TB_CONFIG_GROUPS','ssf_cfg_groups');
define('BS_TB_DESIGN','ssf_config');
define('BS_TB_EVENTS','ssf_events');
define('BS_TB_EVENT_ANN','ssf_events_announcements');
define('BS_TB_FORUMS','ssf_forums');
define('BS_TB_FORUMS_PERM','ssf_forums_perm');
define('BS_TB_INTERN','ssf_intern');
define('BS_TB_LANGS','ssf_languages');
define('BS_TB_LINKS','ssf_links');
define('BS_TB_LINK_VOTES','ssf_links_votes');
define('BS_TB_LOG_ERRORS','ssf_log_errors');
define('BS_TB_LOG_IPS','ssf_log_ips');
define('BS_TB_MODS','ssf_moderators');
define('BS_TB_PMS','ssf_pms');
define('BS_TB_POLL','ssf_polls');
define('BS_TB_POLL_VOTES','ssf_poll_votes');
define('BS_TB_POSTS','ssf_posts');
define('BS_TB_PROFILES','ssf_profiles');
define('BS_TB_RANKS','ssf_user_ranks');
define('BS_TB_SEARCH','ssf_search');
define('BS_TB_SESSIONS','ssf_sessions');
define('BS_TB_SMILEYS','ssf_smileys');
define('BS_TB_SUBSCR','ssf_subscriptions');
define('BS_TB_TASKS','ssf_tasks');
define('BS_TB_THEMES','ssf_themes');
define('BS_TB_THREADS','ssf_topics');
define('BS_TB_UNREAD','ssf_unread');
define('BS_TB_UNREAD_HIDE','ssf_unread_hide');
define('BS_TB_UNSENT_POSTS','ssf_unsent_posts');
define('BS_TB_USER_BANS','ssf_user_bans');
define('BS_TB_USER_FIELDS','ssf_user_fields');
define('BS_TB_USER_GROUPS','ssf_user_groups');
##########################################
?>