<?php
##########################################
###### Generated MySQL-Config-File #######
##########################################
define('BS_MYSQL_HOST','localhost');
define('BS_MYSQL_LOGIN','root');
define('BS_MYSQL_PASSWORD','');
define('BS_MYSQL_DATABASE','bs140');
##########################################

############## MySQL-Tables ############
define('BS_TB_ACP_ACCESS','bs_acp_access');
define('BS_TB_ACTIVATION','bs_activation');
define('BS_TB_ATTACHMENTS','bs_attachments');
define('BS_TB_AVATARS','bs_avatars');
define('BS_TB_BANS','bs_banlist');
define('BS_TB_BBCODES','bs_bbcodes');
define('BS_TB_BOTS','bs_bots');
define('BS_TB_CACHE','bs_cache');
define('BS_TB_CHANGE_EMAIL','bs_change_email');
define('BS_TB_CHANGE_PW','bs_change_pw');
define('BS_TB_CONFIG','bs_cfg');
define('BS_TB_CONFIG_GROUPS','bs_cfg_groups');
define('BS_TB_EVENTS','bs_events');
define('BS_TB_EVENT_ANN','bs_events_announcements');
define('BS_TB_FORUMS','bs_forums');
define('BS_TB_FORUMS_PERM','bs_forums_perm');
define('BS_TB_INTERN','bs_intern');
define('BS_TB_LANGS','bs_languages');
define('BS_TB_LINKS','bs_links');
define('BS_TB_LINK_VOTES','bs_links_votes');
define('BS_TB_LOG_ERRORS','bs_log_errors');
define('BS_TB_LOG_IPS','bs_log_ips');
define('BS_TB_MODS','bs_moderators');
define('BS_TB_PMS','bs_pms');
define('BS_TB_POLL','bs_polls');
define('BS_TB_POLL_VOTES','bs_poll_votes');
define('BS_TB_POSTS','bs_posts');
define('BS_TB_PROFILES','bs_profiles');
define('BS_TB_RANKS','bs_user_ranks');
define('BS_TB_SEARCH','bs_search');
define('BS_TB_SESSIONS','bs_sessions');
define('BS_TB_SMILEYS','bs_smileys');
define('BS_TB_SUBSCR','bs_subscriptions');
define('BS_TB_TASKS','bs_tasks');
define('BS_TB_THEMES','bs_themes');
define('BS_TB_THREADS','bs_topics');
define('BS_TB_UNREAD','bs_unread');
define('BS_TB_UNREAD_HIDE','bs_unread_hide');
define('BS_TB_UNSENT_POSTS','bs_unsent_posts');
define('BS_TB_USER','bs_user');
define('BS_TB_USER_BANS','bs_user_bans');
define('BS_TB_USER_FIELDS','bs_user_fields');
define('BS_TB_USER_GROUPS','bs_user_groups');
##########################################
?>